### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by piclemx** [flipt-io/flipt-client-sdks#130]
Would be awesome to have it with JAVA.

**Comment by markphelps** [comment]
@piclemx we can prioritize a Java client side SDK next. 

Would love to learn more about your usage of Flipt if you have a minute to fill out this [Typeform](https://1ld82idjvlr.typeform.com/to/msI2C6Gc) or wanna chat in our [Discord](https://flipt.io/discord) that would be awesome!

**Comment by yquansah** [comment]
Going to reopen this. We have written the code, but until we actually release and it is on Maven then I will close it.

**Comment by piclemx** [comment]
Awesome! Great news!

**Comment by yquansah** [comment]
It has been published! https://central.sonatype.com/artifact/io.flipt/flipt-client-java
