### ISSUE TITLE
[FLI-934] Investigate alternative node-ffi libraries

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt-client-sdks#200]
See #191 

It seems `node-ffi-api` is not compatible with Node v21+ (https://github.com/node-ffi-napi/node-ffi-napi/issues/267)

We should look into alternative ways to support node v21+ such as https://github.com/Koromix/koffi

<sub>[FLI-934](https://linear.app/flipt/issue/FLI-934/investigate-alternative-node-ffi-libraries)</sub>

**Comment by erka** [comment]
As an option try to switch another fork like https://www.npmjs.com/package/@2060.io/ffi-napi

**Comment by piclemx** [comment]
We also get that with only node `20.12.1`. 

 I guess https://koffi.dev/ or https://github.com/zhangyuang/node-ffi-rs/blob/master/README.md could be interesting.

**Comment by piclemx** [comment]
or the other options will be to used the WASM engine instead of the `ffi` engine.

**Comment by markphelps** [comment]
Yah I'm working on the wasm lib now. Very close just working out some kinks

**Comment by markphelps** [comment]
Fixed in #255

**Comment by markphelps** [comment]
@erka when trying to do the release and run `npm run build` I get the following:

```
flipt-client-sdks/flipt-client-node - [node-ffi-release] » npm run build

> @flipt-io/flipt-client@0.7.0 build
> tsc

node_modules/@types/ffi-napi/index.d.ts:469:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'ffi_type' must be of type 'PFFI_TYPE | undefined', but here has type 'PFFI_TYPE | undefined'.

469         ffi_type?: PFFI_TYPE | undefined;
            ~~~~~~~~

  node_modules/@2060.io/ffi-napi/types/index.d.ts:448:9
    448         ffi_type?: PFFI_TYPE | undefined;
                ~~~~~~~~
    'ffi_type' was also declared here.


Found 1 error in node_modules/@types/ffi-napi/index.d.ts:469
```

Seems there is a types mismatch.

**Comment by markphelps** [comment]
Actually, I think I may have fixed it here: https://github.com/flipt-io/flipt-client-sdks/compare/node-ffi-release

can you give it 👀 ?
