### ISSUE TITLE
[FLI-969] Return error to caller after X times of failed connection

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt-client-sdks#253]
In #204 we fixed the panic that could occur if there is no connectivity to host

However now we simply silently fail and replace with an empty 'document' [https://github.com/flipt-io/flipt-client-sdks/blame/969c177bf90068a28385a944f69a0ef956b62b33/flipt-engine-ffi/src/evaluator/mod.rs#L40](https://github.com/flipt-io/flipt-client-sdks/blame/969c177bf90068a28385a944f69a0ef956b62b33/flipt-engine-ffi/src/evaluator/mod.rs#L40)

We should likely set a default threshold (and/or make it configurable) so that after X times of failing to get the snapshot data that we then return the error up to the calling clients so that its clear what is going on instead of silently failing

I suspect this is what is happening in this thread: [https://discord.com/channels/960634591000014878/1232106900670382160/1232472006394642625](https://discord.com/channels/960634591000014878/1232106900670382160/1232472006394642625)

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-969](https://linear.app/flipt/issue/FLI-969/return-error-to-caller-after-x-times-of-failed-connection)</sub>

**Comment by erka** [comment]
I think we've resolved this
