### ISSUE TITLE
[FLI-770] need sdk flutter

### ISSUE THREAD

**Issue by baseron01** [flipt-io/flipt-client-sdks#32]
null

<sub>[FLI-770](https://linear.app/flipt/issue/FLI-770/need-sdk-flutter)</sub>

**Comment by markphelps** [comment]
@baseron01 would you be interested in helping contribute? We do not have Dart/Flutter experience as a team

**Comment by markphelps** [comment]
@baseron01 our v0.1.0 for our Dart/Flutter SDK was just released: https://pub.dev/packages/flipt_client/versions/0.1.0 🎉 

It only supports Mac / Linux for now, iOS and Android coming next!
