### ISSUE TITLE
[Python] allow pydantic < 3.0 in deps

### ISSUE THREAD

**Issue by FyZzyss** [flipt-io/flipt-client-sdks#34]
Please, update pydantic version pin in [pyproject.toml](https://github.com/flipt-io/flipt-python/blob/8997a2dd5a86344c97b042e4b647a364c1ef7c9f/pyproject.toml#L14) to < 3.0 instead <2.5.0. Pydantic already has 2.5.2 tag.

I start big migration in my company from Pydantic 1.x to 2.5.2 and it's blocked;(

**Comment by markphelps** [comment]
@FyZzyss I'm a python noob, will this work: https://github.com/flipt-io/flipt-client-sdks/pull/36/files ?

**Comment by FyZzyss** [comment]
@markphelps Wow! Thank you for such quick response. 
Yes, this will work

**Comment by FyZzyss** [comment]
@markphelps Will you be create a new tag for https://github.com/flipt-io/flipt-python with updated deps? For quick installation from pypi
