### ISSUE TITLE
Wrong reference query param?

### ISSUE THREAD

**Issue by AleksandrTermenzhy** [flipt-io/flipt-client-sdks#370]
Seems like there should be `reference` query param instead of `ref` here:

https://github.com/flipt-io/flipt-client-sdks/blob/6ab80d0eabb0e7e69b3f966840f9dafc5175b376/flipt-client-browser/src/index.ts#L44C1-L45C1

```diff
if (engine_opts.reference) {
- url = `${url}?ref=${engine_opts.reference}`; // not working, still pulls main
+ url = `${url}?reference=${engine_opts.reference}`; // working as expected
}
```

**Comment by markphelps** [comment]
yah you are right @AleksandrTermenzhy ! will push a fix now

**Comment by AleksandrTermenzhy** [comment]
Thanks @markphelps!

**Comment by markphelps** [comment]
Thanks for reporting @AleksandrTermenzhy ! the new version is going out now in CI
