### ISSUE TITLE
[flipt-client-ruby] Unexpected API Response Change Between v0.10.0 and v0.11.0

### ISSUE THREAD

**Issue by mizoR** [flipt-io/flipt-client-sdks#557]
Hello, thank you for maintaining the `flipt_client` gem. I've encountered a potential issue regarding response format changes between versions `v0.10.0` and `v0.11.0`, and I’d like to ask for clarification.

### Description  
In `v0.10.0` and `v0.11.0`, the API response format differs, which seems to break backward compatibility. Since this is a minor version update, I suspect this might be unintentional.

### Steps to Reproduce  
The difference in behavior can be observed with the following commands:

```ruby
# flipt_client v0.10.0
bin/rails runner 'p [Flipt::VERSION, Flipt::EvaluationClient.new("default", url: ENV.fetch("FLIPT_URL")).list_flags]'
# => ["0.10.0", {"status"=>"success", "result"=>[{"key"=>"flag_variant", "enabled"=>true, "type"=>"VARIANT_FLAG_TYPE"}], "error_message"=>nil}]

bin/rails runner 'p [Flipt::VERSION, Flipt::EvaluationClient.new("default", url: ENV.fetch("FLIPT_URL")).evaluate_batch([])]'
# => ["0.10.0", {"status"=>"success", "result"=>{"responses"=>[], "request_duration_millis"=>0.00019899999999999999}, "error_message"=>nil}]

# flipt_client v0.11.0
bin/rails runner 'p [Flipt::VERSION, Flipt::EvaluationClient.new("default", url: ENV.fetch("FLIPT_URL")).list_flags]'
# => ["0.11.0", [{"key"=>"flag_variant", "enabled"=>true, "type"=>"VARIANT_FLAG_TYPE"}]]

bin/rails runner 'p [Flipt::VERSION, Flipt::EvaluationClient.new("default", url: ENV.fetch("FLIPT_URL")).evaluate_batch([])]'
# => ["0.11.0", {"responses"=>[], "request_duration_millis"=>0.0}]
```

### Expected Behavior  
I would expect the response format to remain consistent across minor version updates. Specifically, the response should include fields like `status` and `error_message`, as seen in `v0.10.0`:  

```ruby
{"status"=>"success", "result"=>..., "error_message"=>nil}
```

### Actual Behavior  
In `v0.11.0`, the response no longer includes the `status` and `error_message` fields. The format has changed to the following:  

```ruby
[{"key"=>"flag_variant", "enabled"=>true, "type"=>"VARIANT_FLAG_TYPE"}]
```

### Environment  
- **gem**: flipt_client  
- **Versions**: v0.10.0 and v0.11.0  
- **Ruby**: v3.3.6  

Since this change appears in a minor version update, I wanted to check if this was an intentional modification or a possible bug.

**Comment by GeorgeMac** [comment]
Hey @mizoR sorry for the disruption here.

I believe this changed as part of a refactor to bring some consistency between the various language clients:
https://github.com/flipt-io/flipt-client-sdks/pull/376

I think the envelope (status/result/error) we had before we a bit of an implementation detail leaking through the client API.
Now the evaluation will actually raise an exception when an error occurs instead.

I appreciate this is perhaps a little non-traditional for a minor update. While we aim to maintain semver as much as possible, while pre v1 this might happen on rare occassions. No plans to break it again anytime soon though.

Apologies again for the disruption!

**Comment by mizoR** [comment]
Thank you for the explanation. Understood!
